### ISSUE TITLE
No permissions using /sc

### ISSUE THREAD

**Issue by RubeVi** [Inkzzz/BungeeStaffChat#1]
<a href="http://gyazo.com/c078d5afb512f6d22af32a8f8a745271"><img src="http://i.gyazo.com/c078d5afb512f6d22af32a8f8a745271.png" /></a>

**Comment by Inkzzz** [comment]
You don't have permission....You need to give the person permission in the bungeecord config.yml file.

**Comment by RubeVi** [comment]
I do it, but i still not having permission

**Comment by Inkzzz** [comment]
Check your permissions etc...It's not a problem on my end.

**Comment by RubeVi** [comment]
<a href="http://gyazo.com/d69d48abae9a6a395bd95a05142304ae"><img src="http://i.gyazo.com/d69d48abae9a6a395bd95a05142304ae.png" /></a>

**Comment by Inkzzz** [comment]
What version of Bungee?

**Comment by RubeVi** [comment]
latest

**Comment by Inkzzz** [comment]
I think I used a old-ish one.
